# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntelbrasProject
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'R.swift'
end

target 'IntelbrasProject' do
  pods
end

target 'IntelbrasProjectTests' do
  pods
  pod 'RxTest'
  pod 'RxBlocking'
end
